Updating `update_formula_version` scripts. (#74)
* Updating `update_formula_version` script.

Summary: Updating `update_formula_version.sh` and `update-formula-version.yaml` to auto update yugabytedb brew formulae.

diff --git a/.github/workflows/update-formula-version.yaml b/.github/workflows/update-formula-version.yaml
--- a/.github/workflows/update-formula-version.yaml
+++ b/.github/workflows/update-formula-version.yaml
@@ -8,7 +8,7 @@ jobs:
     if: github.event.client_payload.prerelease == 'false'
     runs-on: macos-latest
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
     - name: "Configure git"
       run: |
         git config user.name 'YugaByte CI'
@@ -16,16 +16,16 @@ jobs:
     - name: "Extract version number from tag"
       id: extract-version
       run: |
-        tag_name="${{ github.event.client_payload.tag }}"
-        echo "Extracting version number from the tag '${tag_name}'."
-        version_number="${tag_name/v/}"
+        release_name="${{ github.event.client_payload.release }}"
+        echo "Extracting version number from the release_tag '${release_name}'."
+        version_number="${release_name/v/}"
         # Keep dots and count the string length
         dot_count="$(res="${version_number//[^.]/}"; echo "${#res}")"
         if [[ "${dot_count}" -eq 2 ]]; then
           version_number="${version_number}.0"
         fi
         if [[ "$(res="${version_number//[^.]/}"; echo "${#res}")" -ne 3 ]]; then
-          echo "The tag '${tag_name}' is invalid. Expected format: 'v1.2.3' or 'v1.2.3.5'." 1>&2
+          echo "The tag '${release_name}' is invalid. Expected format: 'v1.2.3' or 'v1.2.3.5'." 1>&2
           exit 1
         fi
         echo "Extracted the version number '${version_number}'."
